export const products = [
  // Frutas Frescas
  {
    id: 'FR001',
    name: 'Manzanas Fuji',
    price: 1200,
    description: 'Manzanas Fuji crujientes y dulces, cultivadas en el Valle del Maule. Perfectas para meriendas saludables o como ingrediente en postres.',
    category: 'Frutas Frescas',
    stock: 150,
    unit: 'kg',
    origin: 'Valle del Maule',
    image: '/assets/products/manzana.jpg',
    practices: 'Cultivo sostenible en el Valle del Maule',
    recipes: ['Postres con manzanas', 'Ensaladas de frutas', 'Manzanas al horno', 'Smoothies naturales'],
    onSale: true,
    discountPercentage: 15
  },
  {
    id: 'FR002',
    name: 'Naranjas Valencia',
    price: 1000,
    description: 'Jugosas y ricas en vitamina C, estas naranjas Valencia son ideales para zumos frescos y refrescantes.',
    category: 'Frutas Frescas',
    stock: 200,
    unit: 'kg',
    origin: 'Región de O\'Higgins',
    image: '/assets/products/naranja.jpg',
    practices: 'Cultivo optimizado para máxima dulzura y jugosidad',
    recipes: ['Zumos naturales', 'Ensaladas de frutas', 'Marmelada de naranja', 'Batidos cítricos'],
    onSale: false
  },
  {
    id: 'FR003',
    name: 'Plátanos Cavendish',
    price: 800,
    description: 'Plátanos maduros y dulces, perfectos para el desayuno o como snack energético.',
    category: 'Frutas Frescas',
    stock: 250,
    unit: 'kg',
    origin: 'Zona Norte de Chile',
    image: '/assets/products/platano.jpg',
    practices: 'Cultivo responsable con práctica de comercio justo',
    recipes: ['Batidos de plátano', 'Postres con plátano', 'Desayunos energéticos'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'FR004',
    name: 'Fresas Orgánicas',
    price: 2500,
    description: 'Fresas dulces y jugosas, cultivadas de manera orgánica.',
    category: 'Frutas Frescas',
    stock: 100,
    unit: 'kg',
    origin: 'Sur de Chile',
    image: '/assets/products/platano.jpg',
    practices: 'Cultivo orgánico certificado',
    recipes: ['Postres con fresas', 'Batidos frescos', 'Ensaladas de frutas'],
    onSale: false
  },
  {
    id: 'FR005',
    name: 'Peras Williams',
    price: 1300,
    description: 'Peras jugosas y aromáticas, ideales para consumo directo o postres.',
    category: 'Frutas Frescas',
    stock: 180,
    unit: 'kg',
    origin: 'Valle Central',
    image: '/assets/products/manzana.jpg',
    practices: 'Cultivo tradicional sustentable',
    recipes: ['Peras al vino', 'Ensaladas frescas', 'Postres horneados'],
    onSale: true,
    discountPercentage: 25
  },
  {
    id: 'FR006',
    name: 'Mangos Tommy',
    price: 2800,
    description: 'Mangos maduros y aromáticos, perfectos para postres y batidos.',
    category: 'Frutas Frescas',
    stock: 120,
    unit: 'kg',
    origin: 'Norte de Chile',
    image: '',
    practices: 'Cultivo controlado',
    recipes: ['Batidos tropicales', 'Postres exóticos', 'Salsas frutales'],
    onSale: false
  },
  {
    id: 'FR007',
    name: 'Uvas Thompson',
    price: 1800,
    description: 'Uvas sin semilla, dulces y refrescantes.',
    category: 'Frutas Frescas',
    stock: 150,
    unit: 'kg',
    origin: 'Valle de Aconcagua',
    image: '',
    practices: 'Cultivo tradicional',
    recipes: ['Postres con uvas', 'Macedonias', 'Decoración de platos'],
    onSale: true,
    discountPercentage: 30
  },
  {
    id: 'FR008',
    name: 'Kiwis Hayward',
    price: 2200,
    description: 'Kiwis frescos y nutritivos, ricos en vitamina C.',
    category: 'Frutas Frescas',
    stock: 130,
    unit: 'kg',
    origin: 'Zona Centro-Sur',
    image: '/assets/products/manzana.jpg',
    practices: 'Cultivo sostenible',
    recipes: ['Batidos verdes', 'Ensaladas de frutas', 'Postres saludables'],
    onSale: false
  },
  {
    id: 'FR009',
    name: 'Sandías Sin Semilla',
    price: 3500,
    description: 'Sandías dulces y refrescantes, perfectas para el verano.',
    category: 'Frutas Frescas',
    stock: 80,
    unit: 'unidad',
    origin: 'Valle Central',
    image: '',
    practices: 'Cultivo tradicional',
    recipes: ['Jugos naturales', 'Ensaladas refrescantes', 'Postres frescos'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'FR010',
    name: 'Duraznos Frescos',
    price: 1900,
    description: 'Duraznos jugosos y aromáticos de temporada.',
    category: 'Frutas Frescas',
    stock: 160,
    unit: 'kg',
    origin: 'Valle del Maipo',
    image: '/assets/products/naranja.jpg',
    practices: 'Cultivo tradicional',
    recipes: ['Postres con duraznos', 'Mermeladas caseras', 'Batidos refrescantes'],
    onSale: false
  },

  // Verduras Orgánicas
  {
    id: 'VR001',
    name: 'Zanahorias Orgánicas',
    price: 900,
    description: 'Zanahorias crujientes cultivadas sin pesticidas.',
    category: 'Verduras Orgánicas',
    stock: 100,
    unit: 'kg',
    origin: 'Región de O\'Higgins',
    image: '/assets/products/zanahoria.jpg',
    practices: 'Certificación Orgánica',
    recipes: ['Ensaladas frescas', 'Jugos de zanahoria', 'Sopas nutritivas'],
    onSale: true,
    discountPercentage: 15
  },
  {
    id: 'VR002',
    name: 'Espinacas Frescas',
    price: 700,
    description: 'Espinacas frescas y nutritivas, perfectas para ensaladas.',
    category: 'Verduras Orgánicas',
    stock: 80,
    unit: 'bolsa de 500g',
    origin: 'Cultivos Locales Certificados',
    image: '/assets/products/espinaca.jpg',
    practices: 'Cultivo orgánico certificado',
    recipes: ['Ensaladas verdes', 'Batidos verdes', 'Espinacas salteadas'],
    onSale: false
  },
  {
    id: 'VR003',
    name: 'Pimientos Tricolores',
    price: 1500,
    description: 'Pimientos rojos, amarillos y verdes, ideales para salteados.',
    category: 'Verduras Orgánicas',
    stock: 120,
    unit: 'kg',
    origin: 'Valle Central de Chile',
    image: '/assets/products/pimenton.jpg',
    practices: 'Cultivo sostenible',
    recipes: ['Salteados coloridos', 'Ensaladas gourmet', 'Rellenos de pimientos'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'VR004',
    name: 'Tomates Cherry Orgánicos',
    price: 2000,
    description: 'Tomates cherry dulces y aromáticos.',
    category: 'Verduras Orgánicas',
    stock: 90,
    unit: 'kg',
    origin: 'Invernaderos Certificados',
    image: '',
    practices: 'Cultivo orgánico protegido',
    recipes: ['Ensaladas frescas', 'Salsas caseras', 'Guarniciones'],
    onSale: false
  },
  {
    id: 'VR005',
    name: 'Lechugas Hidropónicas',
    price: 1200,
    description: 'Lechugas crocantes cultivadas en sistema hidropónico.',
    category: 'Verduras Orgánicas',
    stock: 150,
    unit: 'unidad',
    origin: 'Cultivos Hidropónicos Certificados',
    image: '',
    practices: 'Cultivo hidropónico sostenible',
    recipes: ['Ensaladas verdes', 'Wraps saludables', 'Hamburguesas gourmet'],
    onSale: true,
    discountPercentage: 25
  },
  {
    id: 'VR006',
    name: 'Brócoli Orgánico',
    price: 1800,
    description: 'Brócoli fresco rico en nutrientes.',
    category: 'Verduras Orgánicas',
    stock: 100,
    unit: 'unidad',
    origin: 'Campos Orgánicos del Sur',
    image: '',
    practices: 'Cultivo orgánico certificado',
    recipes: ['Salteados de brócoli', 'Sopas cremosas', 'Guarniciones al vapor'],
    onSale: false
  },
  {
    id: 'VR007',
    name: 'Champiñones Orgánicos',
    price: 2500,
    description: 'Champiñones frescos cultivados orgánicamente.',
    category: 'Verduras Orgánicas',
    stock: 80,
    unit: 'kg',
    origin: 'Cultivos Especializados',
    image: '',
    practices: 'Cultivo orgánico controlado',
    recipes: ['Salteados con ajo', 'Rellenos vegetarianos', 'Salsas cremosas'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'VR008',
    name: 'Berenjenas Orgánicas',
    price: 1600,
    description: 'Berenjenas frescas de cultivo orgánico.',
    category: 'Verduras Orgánicas',
    stock: 70,
    unit: 'kg',
    origin: 'Valle Central',
    image: '',
    practices: 'Cultivo orgánico tradicional',
    recipes: ['Parmesana de berenjena', 'Asadas a la parrilla', 'Dips saludables'],
    onSale: false
  },
  {
    id: 'VR009',
    name: 'Acelgas Orgánicas',
    price: 1100,
    description: 'Acelgas frescas de hojas grandes y tallos tiernos.',
    category: 'Verduras Orgánicas',
    stock: 110,
    unit: 'manojo',
    origin: 'Huertos Orgánicos',
    image: '',
    practices: 'Cultivo orgánico certificado',
    recipes: ['Salteados de acelga', 'Tortillas verdes', 'Jugos verdes'],
    onSale: true,
    discountPercentage: 30
  },
  {
    id: 'VR010',
    name: 'Zucchini Orgánico',
    price: 1300,
    description: 'Zucchini fresco de cultivo orgánico.',
    category: 'Verduras Orgánicas',
    stock: 90,
    unit: 'kg',
    origin: 'Huertos Certificados',
    image: '',
    practices: 'Cultivo orgánico sostenible',
    recipes: ['Pasta de zucchini', 'Grillados', 'Chips horneados'],
    onSale: false
  },

  // Productos Orgánicos
  {
    id: 'PO001',
    name: 'Miel Orgánica',
    price: 5000,
    description: 'Miel pura y orgánica producida por apicultores locales.',
    category: 'Productos Orgánicos',
    stock: 50,
    unit: 'frasco de 500g',
    origin: 'Apicultores Locales de Chile',
    image: '/assets/products/miel.png',
    practices: 'Certificación Orgánica',
    recipes: ['Endulzante natural', 'Postres saludables', 'Mascarillas naturales'],
    onSale: true,
    discountPercentage: 15
  },
  {
    id: 'PO002',
    name: 'Quinoa Orgánica',
    price: 4500,
    description: 'Quinoa orgánica de alta calidad.',
    category: 'Productos Orgánicos',
    stock: 100,
    unit: 'kg',
    origin: 'Altiplano Chileno',
    image: '',
    practices: 'Cultivo orgánico tradicional',
    recipes: ['Ensaladas de quinoa', 'Guisos nutritivos', 'Bowls saludables'],
    onSale: false
  },
  {
    id: 'PO003',
    name: 'Aceite de Oliva Extra Virgen',
    price: 6000,
    description: 'Aceite de oliva orgánico de primera presión.',
    category: 'Productos Orgánicos',
    stock: 60,
    unit: 'botella de 500ml',
    origin: 'Valle del Huasco',
    image: '',
    practices: 'Producción orgánica certificada',
    recipes: ['Aderezos caseros', 'Marinados', 'Cocina saludable'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'PO004',
    name: 'Almendras Orgánicas',
    price: 7500,
    description: 'Almendras orgánicas sin sal.',
    category: 'Productos Orgánicos',
    stock: 40,
    unit: 'kg',
    origin: 'Productores Certificados',
    image: '',
    practices: 'Cultivo orgánico sustentable',
    recipes: ['Snacks saludables', 'Leche de almendras', 'Postres veganos'],
    onSale: false
  },
  {
    id: 'PO005',
    name: 'Mermelada Orgánica de Frutos Rojos',
    price: 3500,
    description: 'Mermelada artesanal de frutos rojos orgánicos.',
    category: 'Productos Orgánicos',
    stock: 70,
    unit: 'frasco de 250g',
    origin: 'Productores Locales',
    image: '',
    practices: 'Producción artesanal orgánica',
    recipes: ['Desayunos saludables', 'Postres caseros', 'Yogur con frutas'],
    onSale: true,
    discountPercentage: 25
  },
  {
    id: 'PO006',
    name: 'Granola Artesanal',
    price: 4200,
    description: 'Granola artesanal con ingredientes orgánicos.',
    category: 'Productos Orgánicos',
    stock: 80,
    unit: 'kg',
    origin: 'Productores Locales',
    image: '',
    practices: 'Elaboración artesanal',
    recipes: ['Desayunos energéticos', 'Yogur con granola', 'Postres saludables'],
    onSale: false
  },
  {
    id: 'PO007',
    name: 'Pasta Integral Orgánica',
    price: 2800,
    description: 'Pasta integral elaborada con trigo orgánico.',
    category: 'Productos Orgánicos',
    stock: 90,
    unit: 'paquete de 500g',
    origin: 'Productores Certificados',
    image: '',
    practices: 'Producción orgánica certificada',
    recipes: ['Platos de pasta integral', 'Ensaladas frías', 'Sopas caseras'],
    onSale: true,
    discountPercentage: 20
  },
  {
    id: 'PO008',
    name: 'Té Verde Orgánico',
    price: 3800,
    description: 'Té verde orgánico de alta calidad.',
    category: 'Productos Orgánicos',
    stock: 65,
    unit: 'caja de 20 bolsitas',
    origin: 'Importado Certificado',
    image: '',
    practices: 'Cultivo orgánico tradicional',
    recipes: ['Infusiones calientes', 'Té helado', 'Smoothies verdes'],
    onSale: false
  },
  {
    id: 'PO009',
    name: 'Chocolate Orgánico 70%',
    price: 4500,
    description: 'Chocolate negro orgánico sin aditivos.',
    category: 'Productos Orgánicos',
    stock: 55,
    unit: 'barra de 100g',
    origin: 'Comercio Justo Certificado',
    image: '',
    practices: 'Producción orgánica sustentable',
    recipes: ['Postres de chocolate', 'Bebidas calientes', 'Repostería'],
    onSale: true,
    discountPercentage: 30
  },
  {
    id: 'PO010',
    name: 'Semillas de Chía Orgánicas',
    price: 3200,
    description: 'Semillas de chía orgánicas certificadas.',
    category: 'Productos Orgánicos',
    stock: 75,
    unit: 'paquete de 250g',
    origin: 'Productores Certificados',
    image: '',
    practices: 'Cultivo orgánico certificado',
    recipes: ['Pudín de chía', 'Batidos nutritivos', 'Panificados saludables'],
    onSale: false
  }
];